# Setup
name:         Aalto x HoloLens
tagline:      3D scanning/reconstruction with Hololens, Google Tango and etc.
baseurl:      ""

markdown: kramdown
exclude: ["README.md", "Gemfile", "runserver.sh", "makepost.sh"]
